Clean up HCC branch for LLVM lit tests
ROCm/llvm pull request #137
Opened 2018-03-29 18:59 UTC by david-salinas

2018-03-29 20:43 UTC, scchan requested changes

2018-03-29 20:43 UTC, scchan commented on lib/Target/AMDGPU/AMDGPUTargetMachine.cpp
> +// SALINAS  if (getTargetTriple().getEnvironment() != Triple::HCC)
- remove // SALINAS
- hcc current doesn't need the OCL12 pass so why are we adding it?
- for hcc, we should skip the printf runtime binding pass because hcc's implementation is different than the OCL implementation

2018-03-29 21:12 UTC, david-salinas commented on lib/Target/AMDGPU/AMDGPUTargetMachine.cpp
> +// SALINAS  if (getTargetTriple().getEnvironment() != Triple::HCC)
I left this change in by mistake ... I'll remove it from this PR.   I'll look at the printf RT binding pass too. 
This PR will get the list of failing LIT tests down to about 11, from 44.  There are still a few more I need to address.

2018-04-04 20:14 UTC, scchan commented
The merge commits from amd-hcc make this PR quite messy.  It's unnecessary to pull in those changes and the commit message is not really describing what it has been done.  Could you please clean it up and resubmit?  thanks

2018-04-04 20:14 UTC, closed without merging