Replace EraseNonKernel
ROCm/llvm pull request #89
Opened 2017-07-03 16:17 UTC by AlexVlx

This handles the LLVM part of removing usage of a whitelist from HCC. To wit,
it aims to replace the EraseNonKernel pass with a new pass which tries to 
build the transitive closure of all [[hc]] functions in a module, by way of 
DFS. Everything that is not part of the closure is subsequently removed. If 
a non-inlineable function is in the closure, this is an error by virtue of 
non-existing call support. At finalization all functions in the closure are 
marked as AlwaysInline. This is done so as to make it possible to get full 
inlining solely with the AlwaysInliner, without needing the more expensive 
full Inliner. The intended sequencing for the pass is that it runs on the 
fully linked bitcode, immediately before invoking AMDGPU / LC.

2017-07-05 18:44 UTC, yxsamliu commented
LGTM. Thanks.

2017-07-05 18:54 UTC, whchung commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +        unordered_set<Function*> f_;
@AlexVlx could we have a more meaningful name for this set?

2017-07-05 20:31 UTC, whchung requested changes
@AlexVlx The pass looks fine to me. If you could replace `f_` with a more readable name that would make the logic even more comprehensible.

2017-07-05 20:33 UTC, scchan approved these changes
found a typo; otherwise LGTM

2017-07-05 20:33 UTC, scchan commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +// expected to be run by an accelerator i.e. referenced directly of indirectly
I think there's a typo here:  "directly **or** indirectly"

2017-07-12 14:16 UTC, AlexVlx commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +// expected to be run by an accelerator i.e. referenced directly of indirectly
Whoops - thank you for pointing it out, fixed!

2017-07-12 14:17 UTC, AlexVlx commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +        unordered_set<Function*> f_;
Done, thanks for pointing it out.

2017-10-04 16:39 UTC, whchung approved these changes
LGTM

2017-10-04 16:39 UTC, whchung commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +                x.addFnAttr(Attribute::AlwaysInline);
this is where you all functions visited by HC kernels/functions with `alwaysinline` attribute.

2017-10-04 16:39 UTC, whchung commented on lib/Transforms/HC/SelectAcceleratorCode/SelectAcceleratorCode.cpp
> +// more expensive full Inliner pass.
@AlexVlx thanks for putting comments in this pass. It answers one question i had in the PR for `hcc`.

2017-10-06 15:11 UTC, scchan approved these changes

2017-10-06 15:11 UTC, merged